version: 2.1
orbs:
  node: circleci/node@5

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout  # đảm bảo có code để lấy file deploy.sh
      - run:
          name: Deploy to EC2 server
          command: |
            ssh -v -o StrictHostKeyChecking=no ubuntu@18.234.222.55 'bash -s' < .circleci/deploy.sh

workflows:
  build-and-deploy:
    jobs:
      - deploy
