version: 2.1
orbs:
  node: circleci/node@5

jobs:
  test-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test # hoặc command bạn muốn dùng để test

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Deploy to EC2 server
          command: |
            ssh -v -o StrictHostKeyChecking=no ubuntu@18.234.222.55 'bash -s' < ./deploy.sh

workflows:
  build-and-deploy:
    jobs:
      - test-node
      - deploy:
          requires:
            - test-node
